Repository 2025-Trendithon-Omnivore2/2025-Trendithon-Omnivore2-FrontEnd, pull requests merged in 2025-02, with the labels that each got.

#1 [Feat]#1-프로젝트 첫 세팅
  .DS_Store
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  eslint.config.js
  index.html
  package-lock.json
  package.json
  public/images/header/HeaderLogo.png
  public/images/header/HeaderLogoLeft.png
  public/images/header/HeaderLogoRight.png
  src/.DS_Store
  src/App.tsx
  src/assets/react.svg
  src/components/navigation/footer/Footer.styled.ts
  src/components/navigation/footer/Footer.tsx
  src/components/navigation/header/Header.styled.ts
  src/components/navigation/header/Header.tsx
  src/index.css
  src/layout/DefaultLayout.tsx
  src/layout/RootLayout.tsx
  src/main.tsx
  src/pages/.DS_Store
  src/pages/dailyCake/DailyCake.tsx
  src/pages/digitalCake/DigitalCake.tsx
  src/pages/login/Login.tsx
  src/pages/mypage/Mypage.tsx
  src/routes/GuestRoute.tsx
  src/routes/ProtectedRoute.tsx
  src/routes/router.tsx
  src/styles/globalStyle.ts
  src/vite-env.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: ✨ Feature, 🐰 찬주

#3 [Chore]#1 - 배포 관련 redirects 파일 생성
  public/_redirects
Labels: 🐰 찬주, 👷🏻‍♀️ Chore

#6 [Feat]#4-button component create
  index.html
  public/images/favicon.ico
  src/App.tsx
  src/components/button/Button.styled.ts
  src/components/button/Button.tsx
  src/lib/types/style.ts
  src/pages/login/Login.tsx
  src/styles/theme.ts
Labels: ✨ Feature, 🐰 찬주, 🎨 Design

#11 [Feat]#8 로그인
  public/images/Login/cake.png
  public/images/Login/google.png
  public/images/Login/kakao.png
  src/pages/login/Login.styled.ts
  src/pages/login/Login.tsx
  src/styles/globalStyle.ts
Labels: ✨ Feature, 🐰 찬주, 🎨 Design

#36 [Fix] #35 짜잘한 오류 수정
  src/components/button/DroptDownButton.styled.ts
  src/components/goDetailBar/GoDetailBar.tsx
  src/pages/dailyCake/DailyCake.styled.ts
  src/pages/dailyCake/DailyCake.tsx
  src/pages/mypage/Mypage.styled.ts
  src/pages/mypage/Mypage.tsx
Labels: 🐶 민우, 🐛 Fix

#39 [Feat] #37 소셜 페이지 UI 구현
  src/components/selectTap/SelectTap.styled.ts
  src/components/selectTap/SelectTap.tsx
  src/components/social/socialCake/SocialCake.styled.ts
  src/components/social/socialCake/SocialCake.tsx
  src/components/social/socialCupcake/SocialCupcake.styled.ts
  src/components/social/socialCupcake/SocialCupcake.tsx
  src/pages/social/Social.styled.ts
  src/pages/social/Social.tsx
  src/routes/router.tsx
  tsconfig.json
Labels: ✨ Feature, 🐶 민우, 🎨 Design

#49 [Feat] #43 - 소셜 페이지 api 연결 구현
  src/apis/domain/social/getSocialCakes.ts
  src/apis/domain/social/getSocialCupcakes.ts
  src/pages/social/Social.tsx
Labels: ✨ Feature, 🐶 민우

#50 [Feat] #42 - 컵케이크 페이지 api 연결
  public/images/cupCake/check_icon.svg
  public/images/cupCake/nervous_cupcake.svg
  public/images/cupCake/so_so_cupcake.svg
  src/apis/domain/cupcake/getAccessRange.ts
  src/apis/domain/cupcake/getCupCake.ts
  src/apis/domain/cupcake/getMyCupcakes.ts
  src/apis/domain/cupcake/postCupCake.ts
  src/apis/domain/cupcake/updateAccess.ts
  src/apis/domain/mypage/getMyInfo.ts
  src/apis/domain/mypage/updateMyInfo.ts
  src/apis/instance.ts
  src/components/calendar/Calendar.styled.ts
  src/components/calendar/Calendar.tsx
  src/components/digitalCake/digitalCakeModal.tsx
  src/components/inputBar/InputBar.tsx
  src/components/modal/Modal.styled.ts
  src/components/modal/Modal.tsx
  src/components/modal/createDailyCake/CreateDailyCake.styled.ts
  src/components/modal/createDailyCake/CreateDailyCake.tsx
  src/pages/dailyCake/DailyCake.tsx
  src/pages/mypage/Mypage.styled.ts
  src/pages/mypage/Mypage.tsx
Labels: ✨ Feature, 🐶 민우, 🎨 Design

#52 [Feature]#46-myCake api
  src/apis/domain/cake/getCakeInfo.ts
  src/apis/domain/cake/postCake.ts
  src/apis/domain/digitalCake/postCakeCandles.ts
  src/apis/instance.ts
  src/components/digitalCake/digitalCakeModal.styled.ts
  src/components/digitalCake/digitalCakeModal.tsx
  src/components/digitalCake/digitalCakeModalNoContent.tsx
  src/constants/cakeColorConstants.ts
  src/constants/candleData.ts
  src/hooks/handleShare.ts
  src/pages/digitalCake/DigitalCake.styled.ts
  src/pages/digitalCake/DigitalCake.tsx
  src/pages/intro/Result.tsx
  tsconfig.json
  vite.config.js
  vite.config.ts
Labels: ✨ Feature, 🐰 찬주, ♻️ Refactor

#51 [Feat] 마이페이지 api 구현
  src/apis/domain/mypage/deleteFriend.ts
  src/apis/domain/mypage/deleteFriendReq.ts
  src/apis/domain/mypage/getMyFollowers.ts
  src/apis/domain/mypage/getRequestFriends.ts
  src/apis/domain/mypage/postAcceptFriend.ts
  src/apis/domain/mypage/postFriendRequest.ts
  src/components/friends/friendsManageForm/FriendsManageForm.tsx
  src/pages/mypage/Mypage.tsx
  src/pages/mypage/detailFriends/DetailFriends.tsx
  src/pages/mypage/friendRequest/FriendRequest.tsx
Labels: ✨ Feature, 🐶 민우, 🎨 Design

#58 [Feat] Social Cupcake 조회 기능 및 친구 요청 수락, 거절 기능
  src/apis/domain/mypage/deleteFriend.ts
  src/apis/domain/mypage/deleteFriendReq.ts
  src/apis/domain/mypage/getMyFollowers.ts
  src/apis/domain/mypage/getRequestFriends.ts
  src/apis/domain/social/getCakeInfoByMemberid.ts
  src/apis/domain/social/getSocialCakes.ts
  src/apis/domain/social/getSocialCupcakes.ts
  src/components/friends/friendsBar/FriendsBar.tsx
  src/components/friends/friendsManageForm/FriendsManageForm.tsx
  src/components/friends/friendsRequestBox/FriendsRequestBox.tsx
  src/components/inputBar/InputBar.tsx
  src/components/socialCupcake/SocialSingleCupcake.styled.ts
  src/components/socialCupcake/SocialSingleCupcake.tsx
  src/pages/mypage/Mypage.tsx
  src/pages/mypage/detailFriends/DetailFriends.tsx
  src/pages/mypage/friendRequest/FriendReqeust.styled.ts
  src/pages/mypage/friendRequest/FriendRequest.tsx
  src/pages/social/Social.styled.ts
  src/pages/social/Social.tsx
Labels: ✨ Feature, 🐶 민우, 🐛 Fix

#61 [Style] #43 - 팔로워 컵케이크 nickname 추가
  src/components/socialCupcake/SocialSingleCupcake.styled.ts
  src/components/socialCupcake/SocialSingleCupcake.tsx
  src/pages/social/Social.tsx
Labels: 🐶 민우, 🎨 Design, 🐛 Fix

#62 [Feat] #43 - social cake dummy 처리
  src/components/social/socialCake/SocialCake.styled.ts
  src/pages/social/Social.tsx
Labels: 🐶 민우, 🎨 Design, 🐛 Fix

#65 [Feat] 소셜 케이크 조회, 소셜 좋아요 구현
  src/apis/domain/cake/postLikeCake.ts
  src/apis/domain/cupcake/postLikeCupcake.ts
  src/apis/domain/social/getSocialCakes.ts
  src/components/social/socialCake/SocialCake.styled.ts
  src/components/social/socialCake/SocialCake.tsx
  src/components/socialCupcake/SocialSingleCupcake.tsx
  src/pages/social/Social.styled.ts
  src/pages/social/Social.tsx
Labels: ✨ Feature, 🐶 민우, 🎨 Design, 🐛 Fix

#66 [Refactor] 모달 창 안에서도 좋아요 누를 수 있도록 수정
  src/components/socialCupcake/SocialSingleCupcake.tsx
  src/pages/social/Social.styled.ts
  src/pages/social/Social.tsx
Labels: 🐶 민우, ♻️ Refactor

#75 [Fix] #72 - Calendar 요일 순서 수정
  src/components/calendar/Calendar.tsx
Labels: 🐶 민우, 🐛 Fix
